### PR TITLE
Added TACGRP.TSK.CNT / CONTAIN Graphic (G*T*J-----****X)

### PR DESCRIPTION
**Pull request by Vac1911**
Added TACGRP.TSK.CNT / CONTAIN Graphic (G*T*J-----****X).
Also added quick geometry function to test if a set of points are clockwise.

_I am opening a pull request to your fork (rather than the main repo) as I plan to create boundary/line based contributions in the future. This is just me getting my feet wet in this project._

Screen shot of added graphic (example data included in /example-data/tacticaljson/contain.json):
image

### CODE REVIEW

**Comment by Vac1911** [comment]
I didn't realize the "Added Counterattack" commit was going to be added to the pull request because it was made after the pull request was created but, here is an image of that:
image

**Review by ondrej-podolsky — APPROVED** [review]
LGTM, thank you for solving this!

**Comment by Plavit** [comment]
Great work @Vac1911 , thanks for contributing!

**Comment by Vac1911** [comment]
No problem :D

**Pull request merged**
